fix(ci-cd): update pull request diff retrieval method and add error check

diff --git a/.github/workflows/pr-review.yml b/.github/workflows/pr-review.yml
--- a/.github/workflows/pr-review.yml
+++ b/.github/workflows/pr-review.yml
@@ -15,13 +15,6 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: "Get Diff"
-        id: get_diff
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const diff = await github.request('GET ${{ github.event.pull_request.diff_url }}');
-            core.setOutput('pull_request_diff', `pull_request_diff<<EOF\n${diff.data}\nEOF`);
       - uses: Stone-IT-Cloud/gemini-code-review-action@0.0.2
         name: "Code Review by Gemini AI"
         id: review
@@ -32,8 +25,12 @@ jobs:
           github_pull_request_number: ${{ github.event.pull_request.number }}
           git_commit_hash: ${{ github.event.pull_request.head.sha }}
           model: "gemini-1.5-pro-latest"
-          pull_request_diff: |-
-            ${{ steps.get_diff.outputs.pull_request_diff }}
+          pull_request_diff: ${{ github.event.pull_request.diff }}
           extra_prompt: |-
             Please write your review in English as an experienced Golang developer.
-          log_level: "DEBUG"
+          log_level: "INFO"
+      - name: Check for errors (example)
+        if: steps.review.outcome != 'success'
+        run: |
+          echo "Gemini review failed!"
+          exit 1
